import {createElement} from 'react';
import {Episode, EpisodeShell, episodeFrames} from './Shell';
import * as V from './visuals';
import * as V2 from './visuals2';
import * as V3 from './visuals3';

const MAC = 'Music: Kevin MacLeod (incompetech.com) · CC BY 4.0';

export const EPISODES: Record<string, Episode> = {
  ep01: {
    n: '01',
    hook: 'كل معلومة تقريباً… لها مكانٌ على الأرض',
    hookEn: 'Almost every piece of information has a place on Earth',
    HookVisual: V.V_Globe,
    beats: [
      {kicker: 'التعريف', title: 'ما هي البيانات الجيومكانية؟', body: 'أي معلومة مرتبطة بموقع على سطح الأرض: ماذا يوجد؟ وأين؟ ومتى؟', Visual: V.V_Equation},
      {kicker: 'المصادر', title: 'من أين تأتي؟', body: 'من الأقمار الصناعية وأنظمة الملاحة والطائرات المسيّرة والمسح الأرضي والحساسات.', Visual: V.V_Sources},
      {kicker: 'الأشكال', title: 'نقاط وخطوط ومساحات… وصور', body: 'البيانات المتجهية ترسم المعالم بدقة، والبيانات الشبكية (الصور) تغطي كل شبر.', Visual: V.V_Forms},
      {kicker: 'الاستخدامات', title: 'أين نستخدمها؟', body: 'في كل قرار يعتمد على المكان: من تخطيط المدن… إلى الاستجابة للطوارئ.', Visual: V.V_Uses},
    ],
    takeaway: 'حين تعرف «أين»… تفهم «لماذا»',
    music: 'music/inspired.mp3',
    volume: 0.3,
    source: `Imagery: NASA (Galileo, ISS) · Map data © OpenStreetMap contributors · ${MAC} — "Inspired"`,
  },
  ep02: {
    n: '02',
    hook: '«صورة فضائية عالية الدقة»… أي دقة نقصد؟',
    hookEn: 'High-resolution satellite image — which resolution?',
    HookVisual: V.V_Question,
    beats: [
      {kicker: '1 · الدقة المكانية', title: 'حجم البكسل على الأرض', body: 'كم متراً يغطي البكسل الواحد؟ كلما صغر البكسل… ظهرت تفاصيل أدق.', Visual: V.V_Spatial},
      {kicker: '2 · الدقة الطيفية', title: 'كم «لوناً» يرى المستشعر؟', body: 'بعض المستشعرات ترى ما بعد الضوء المرئي، مثل الأشعة تحت الحمراء التي تكشف صحة النبات.', Visual: V.V_Spectral},
      {kicker: '3 · الدقة الزمنية', title: 'متى يعود القمر للمكان نفسه؟', body: 'Landsat يعود كل 16 يوماً، وزوج أقمار Sentinel-2 كل 5 أيام عند خط الاستواء.', Visual: V.V_Temporal},
      {kicker: '4 · الدقة الإشعاعية', title: 'كم درجة سطوع يميّز؟', body: 'كلما زادت البتات… رأى المستشعر فروقاً أدق بين الظلال والإضاءة.', Visual: V.V_Radiometric},
    ],
    takeaway: 'الدقة ليست رقماً واحداً… اختر البيانات حسب سؤالك',
    music: 'music/floating-cities.mp3',
    volume: 0.35,
    source: `Imagery: NASA ISS crew photography (pixelation illustrative) · ${MAC} — "Floating Cities"`,
  },
  ep03: {
    n: '03',
    hook: 'كيف نعرف صحة مزرعة… من مئات الكيلومترات؟',
    hookEn: 'How do we check a farm’s health from orbit?',
    HookVisual: V.V_Farm,
    beats: [
      {kicker: 'المبدأ', title: 'النبات الصحي «يلمع» بالأشعة تحت الحمراء', body: 'الكلوروفيل يمتص الضوء الأحمر، بينما تعكس أوراق النبات السليمة الأشعة تحت الحمراء القريبة بقوة.', Visual: V.V_Leaf},
      {kicker: 'المؤشر', title: 'NDVI', body: 'مؤشر بسيط يقارن النطاقين: قيمه من −1 إلى +1، وكلما اقترب من +1 كان الغطاء النباتي أكثف.', Visual: V.V_Formula},
      {kicker: 'مثال', title: 'حقول الجوف من الفضاء', body: 'في صور الألوان الكاذبة يظهر النبات بالأحمر… فتبدو الحقول الدائرية واضحة في قلب الصحراء.', Visual: V.V_Jowf},
      {kicker: 'الاستخدامات', title: 'ماذا نستفيد؟', body: 'متابعة المحاصيل، ورصد الجفاف مبكراً، وترشيد المياه… على مساحات لا يغطيها أي فريق ميداني.', Visual: V.V_AgriUses},
    ],
    takeaway: 'ما لا تراه العين… يقيسه المستشعر',
    music: 'music/clean-soul.mp3',
    volume: 0.4,
    trimBefore: 34,
    source: `Imagery: NASA/JPL (Terra ASTER, Landsat) · ${MAC} — "Clean Soul"`,
  },
  ep04: {
    n: '04',
    hook: 'ماذا تخبرنا أضواء الليل… من الفضاء؟',
    hookEn: 'What do night lights tell us from space?',
    HookVisual: V.V_Night,
    beats: [
      {kicker: 'القياس', title: 'الأقمار تقيس الضوء ليلاً', body: 'مستشعرات حساسة تلتقط أضواء المدن والطرق والمنشآت، لتصنع خرائط مثل «الرخام الأسود» من NASA.', Visual: V.V_Arabia},
      {kicker: 'القراءة', title: 'أين تتركز الحياة؟', body: 'تظهر المدن الكبرى بوضوح، وتظهر الطرق بينها كخيوط من الضوء.', Visual: V.V_Clusters},
      {kicker: 'المعنى', title: 'الضوء مؤشر تقريبي', body: 'يرتبط سطوع الليل غالباً بالكثافة السكانية والنشاط الاقتصادي، لذلك يستخدمه الباحثون مؤشراً مساعداً.', Visual: V.V_Proxy},
      {kicker: 'الاستخدامات', title: 'لماذا يهم؟', body: 'لرصد التوسع العمراني، وتخطيط الكهرباء، وتقدير السكان، ومتابعة التعافي بعد الكوارث.', Visual: V.V_LightUses},
    ],
    takeaway: 'خريطة الضوء… نافذة على حركة الحياة',
    music: 'music/dreams-become-real.mp3',
    volume: 0.4,
    trimBefore: 41,
    source: `Imagery: NASA Black Marble 2016 · NASA ISS crew photography · ${MAC} — "Dreams Become Real"`,
  },
  ep05: {
    n: '05',
    hook: 'لماذا لا تدور كل الأقمار على الارتفاع نفسه؟',
    hookEn: 'Why don’t all satellites fly at the same height?',
    HookVisual: () => V.Photo({src: 'space/apollo17-red-sea.jpg'}),
    beats: [
      {kicker: '1 · المدار المنخفض', title: 'قريب وسريع', body: 'من 160 إلى 2,000 كم. يدور حول الأرض في نحو ساعة ونصف، ومثالي لتصوير الأرض بدقة عالية.', Visual: V2.orbitVisual(0)},
      {kicker: '2 · المدار المتوسط', title: 'بيت أقمار الملاحة', body: 'تدور أقمار GPS على نحو 20,200 كم، فيرى كل قمر مساحة واسعة من الأرض.', Visual: V2.orbitVisual(1)},
      {kicker: '3 · المدار الثابت', title: 'ثابت فوق نقطة واحدة', body: 'على 35,786 كم فوق خط الاستواء يدور بسرعة دوران الأرض نفسها… فيبدو ثابتاً في السماء.', Visual: V2.orbitVisual(2)},
      {kicker: 'المقارنة', title: 'لكل مدار مهمة', body: 'المنخفض للرصد والصور، والمتوسط للملاحة، والثابت للاتصالات والأرصاد الجوية.', Visual: V2.orbitVisual(-1)},
    ],
    takeaway: 'لكل مهمة… مدارها',
    music: 'music/floating-cities.mp3',
    volume: 0.35,
    trimBefore: 20,
    source: `Imagery: NASA Apollo 17 · Orbit diagram not to scale · ${MAC} — "Floating Cities"`,
  },
  ep06: {
    n: '06',
    hook: 'كيف يعرف جوالك مكانك… بدقة أمتار؟',
    hookEn: 'How does your phone know where you are?',
    HookVisual: V.V_Night,
    beats: [
      {kicker: '1 · الإشارة', title: 'الأقمار تبث الوقت والموقع', body: 'كل قمر ملاحة يرسل باستمرار رسالة فيها هويته، وموقعه، والوقت الدقيق لحظة الإرسال.', Visual: V2.V_Signal},
      {kicker: '2 · المسافة', title: 'من زمن الوصول… نحسب البعد', body: 'يقيس الجهاز كم استغرقت الإشارة، ثم يضربه في سرعة الضوء ليعرف بعده عن القمر.', Visual: V2.V_Distance},
      {kicker: '3 · التقاطع', title: 'ثلاث مسافات… نقطة واحدة', body: 'معرفة بعدك عن ثلاثة أقمار تحصر موقعك في نقطة واحدة. هذا ما يسمى التثليث.', Visual: V2.V_Trilat},
      {kicker: '4 · القمر الرابع', title: 'لتصحيح ساعة جهازك', body: 'ساعة جوالك أقل دقة بكثير من الساعات الذرية في الأقمار، والإشارة الرابعة تصحح هذا الفرق.', Visual: V2.V_Clock},
    ],
    takeaway: 'موقعك… مسألة توقيت دقيق',
    music: 'music/tech-talk.mp3',
    volume: 0.25,
    trimBefore: 14,
    source: `Imagery: NASA ISS crew photography · Diagrams illustrative · ${MAC} — "Tech Talk"`,
  },
  ep07: {
    n: '07',
    hook: 'كيف كبرت الرياض؟ الأرشيف الفضائي يجيب',
    hookEn: 'How did Riyadh grow? The satellite archive answers',
    HookVisual: V.V_Night,
    beats: [
      {kicker: '1972', title: 'مدينة صغيرة في قلب نجد', body: 'صورة من القمر Landsat عام 1972، حين كان عدد السكان نحو نصف مليون نسمة.', Visual: V2.yearPhoto('space/riyadh-1972.jpg', '1972', 'Landsat MSS')},
      {kicker: '1990', title: 'المدينة تمتد في كل اتجاه', body: 'بعد 18 عاماً: شبكة طرق واسعة وأحياء جديدة تتوزع حول المركز.', Visual: V2.yearPhoto('space/riyadh-1990.jpg', '1990', 'Landsat TM')},
      {kicker: '2000', title: 'أكثر من مليوني نسمة', body: 'المساحة نفسها تقريباً (27 × 34 كم)… وقد امتلأت بالعمران.', Visual: V2.yearPhoto('space/riyadh-2000.jpg', '2000', 'Terra ASTER')},
      {kicker: 'القيمة', title: 'لماذا يهم الأرشيف؟', body: 'مقارنة الصور عبر السنين تكشف اتجاهات النمو، وتساعد على تخطيط الطرق والمدارس والمياه والإسكان.', Visual: () => V.Chips({items: [['اتجاهات النمو', 'Growth trends'], ['تخطيط الطرق', 'Road planning'], ['الخدمات العامة', 'Public services'], ['الإسكان', 'Housing']]})},
    ],
    takeaway: 'الأرشيف الفضائي… ذاكرة المدن',
    music: 'music/movement-proposition.mp3',
    volume: 0.3,
    source: `Imagery: NASA/JPL PIA11087 (Landsat MSS 1972, Landsat TM 1990, ASTER 2000) · ${MAC} — "Movement Proposition"`,
  },
  ep08: {
    n: '08',
    hook: 'كيف نرسم الجبال… بالأرقام؟',
    hookEn: 'How do we draw mountains with numbers?',
    HookVisual: V2.V_Dem3d,
    beats: [
      {kicker: 'التعريف', title: 'نموذج الارتفاع الرقمي (DEM)', body: 'شبكة من الخلايا، في كل خلية رقم واحد: ارتفاع الأرض عن سطح البحر.', Visual: V2.V_DemNumbers},
      {kicker: 'التلوين', title: 'من الأرقام… إلى صورة', body: 'نلوّن كل خلية حسب ارتفاعها: الكحلي للمنخفضات، والأبيض للقمم.', Visual: V2.V_DemColor},
      {kicker: 'البعد الثالث', title: 'عسير كما لم ترها', body: 'الأرقام نفسها تتحول إلى مجسّم ثلاثي الأبعاد، من ساحل تهامة إلى قمم تقارب 3,000 م.', Visual: V2.V_Dem3d},
      {kicker: 'الاستخدامات', title: 'أين نستخدمه؟', body: 'في رسم مسارات السيول، وتخطيط الطرق، واختيار مواقع الأبراج، ومشاريع الطاقة.', Visual: () => V.Chips({items: [['مسارات السيول', 'Flood paths'], ['تخطيط الطرق', 'Road design'], ['مواقع الأبراج', 'Tower siting'], ['الطاقة المتجددة', 'Renewables']]})},
    ],
    takeaway: 'الارتفاع… البعد الثالث للخريطة',
    music: 'music/echoes-of-time.mp3',
    volume: 0.35,
    trimBefore: 8,
    source: `Elevation: AWS Terrain Tiles (Mapzen; SRTM & others) · 3D view vertically exaggerated · ${MAC} — "Echoes of Time"`,
  },
  ep09: {
    n: '09',
    hook: 'ماذا لو غطّت الغيوم المكان… أو حلّ الليل؟',
    hookEn: 'What if clouds cover the area — or night falls?',
    HookVisual: V2.V_Clouds,
    beats: [
      {kicker: 'المشكلة', title: 'الكاميرا تحتاج ضوء الشمس', body: 'الأقمار البصرية تلتقط الضوء المنعكس، فلا ترى ليلاً، وتحجبها الغيوم.', Visual: V2.V_Clouds},
      {kicker: 'الحل', title: 'الرادار يصنع ضوءه بنفسه', body: 'يرسل نبضات من الموجات الدقيقة ويستقبل صداها، فيعمل ليلاً ونهاراً وعبر الغيوم.', Visual: V2.V_Radar},
      {kicker: 'مثال', title: 'آثار قوافل في الربع الخالي', body: 'في صور الرادار لمنطقة «أوبار» ظهرت مسارات قوافل قديمة بوضوح، وساعدت في تحديد موقع المدينة المفقودة.', Visual: V2.V_Ubar},
      {kicker: 'الاستخدامات', title: 'أين يتفوّق الرادار؟', body: 'في رصد السيول، وقياس هبوط الأرض بدقة عالية، وتتبع السفن، ورسم التضاريس.', Visual: () => V.Chips({items: [['السيول والفيضانات', 'Floods'], ['هبوط الأرض', 'Ground subsidence'], ['تتبع السفن', 'Ship detection'], ['رسم التضاريس', 'Topography']]})},
    ],
    takeaway: 'حين تغيب الشمس… يرى الرادار',
    music: 'music/interloper.mp3',
    volume: 0.35,
    trimBefore: 1.5,
    source: `Imagery: NASA JPL PIA01302 (SIR-C/X-SAR, Ubar) · USGS/NASA Landsat 7 · ${MAC} — "Interloper"`,
  },
  ep10: {
    n: '10',
    hook: 'لماذا تبدو غرينلاند بحجم أفريقيا… على الخريطة؟',
    hookEn: 'Why does Greenland look as big as Africa?',
    HookVisual: V.V_Globe,
    beats: [
      {kicker: 'المشكلة', title: 'الكرة لا تُسطَّح بلا تشويه', body: 'مثل قشرة البرتقال: إما أن تتمزق، أو تتمطّط الأشكال. لذلك كل خريطة مسطحة فيها تشويه ما.', Visual: V2.V_Peel},
      {kicker: 'مركاتور', title: 'يكبّر المساحات قرب القطبين', body: 'إسقاط مركاتور يحافظ على الاتجاهات، لكنه يضخّم المساحات كلما ابتعدنا عن خط الاستواء.', Visual: V2.V_Mercator},
      {kicker: 'الحقيقة', title: 'أفريقيا أكبر بنحو 14 مرة', body: 'مساحة أفريقيا نحو 30 مليون كم²، ومساحة غرينلاند نحو 2.2 مليون كم² فقط.', Visual: V2.V_Greenland},
      {kicker: 'الاختيار', title: 'الإسقاط حسب الاستخدام', body: 'مركاتور للملاحة، والإسقاطات متساوية المساحة للإحصاءات، وUTM للأعمال الهندسية الدقيقة.', Visual: () => V.Chips({items: [['مركاتور: الملاحة', 'Mercator · navigation'], ['متساوي المساحة', 'Equal-area · statistics'], ['UTM: الهندسة', 'UTM · engineering'], ['مخصص للمنطقة', 'Local projections']]})},
    ],
    takeaway: 'كل خريطة… اختيار',
    music: 'music/inspired.mp3',
    volume: 0.3,
    trimBefore: 30,
    source: `Imagery: NASA Galileo · Areas approximate · ${MAC} — "Inspired"`,
  },
  ep11: {
    n: '11',
    hook: 'كيف نراقب الشعاب المرجانية… من الفضاء؟',
    hookEn: 'How do we monitor coral reefs from space?',
    HookVisual: () => V.Photo({src: 'space/nw-coast-reefs.jpg'}),
    beats: [
      {kicker: 'الثروة', title: 'شعاب البحر الأحمر', body: 'في ضفّة الوجه وحدها قرابة 260 نوعاً من المرجان، بحسب وصف NASA لهذه الصورة.', Visual: V2.V_Wajh},
      {kicker: 'المبدأ', title: 'الماء الصافي نافذة', body: 'في المياه الضحلة الصافية يصل الضوء إلى القاع ويعود، فتظهر الشعاب في الصور الفضائية.', Visual: V2.V_Shallow},
      {kicker: 'المتابعة', title: 'مقارنة عبر السنوات', body: 'تكرار التصوير يكشف التغيّر في امتداد الشعاب ولونها، ويساعد على رصد المناطق المهددة مبكراً.', Visual: () => V.Photo({src: 'space/al-wajh-bank.jpg', zoom: [1.4, 1.1], pos: '30% 40%'})},
      {kicker: 'الاستخدامات', title: 'لماذا يهم؟', body: 'لحماية البيئة البحرية، وتخطيط السواحل، والسياحة البيئية، وسلامة الملاحة في المياه الضحلة.', Visual: () => V.Chips({items: [['حماية البيئة', 'Conservation'], ['تخطيط السواحل', 'Coastal planning'], ['السياحة البيئية', 'Eco-tourism'], ['سلامة الملاحة', 'Safe navigation']]})},
    ],
    takeaway: 'تحت سطح الماء… بيانات تستحق الحماية',
    music: 'music/spacial-harvest.mp3',
    volume: 0.35,
    trimBefore: 2,
    source: `Imagery: NASA ISS crew photography (Al Wajh Bank, NW coast) · ${MAC} — "Spacial Harvest"`,
  },
  ep12: {
    n: '12',
    hook: 'كم بكسلاً تحتاج لتصوير المملكة كاملة؟',
    hookEn: 'How many pixels to image the whole Kingdom?',
    HookVisual: V.V_Question,
    beats: [
      {kicker: 'نقطة البداية', title: 'مساحة المملكة', body: 'نحو 2.15 مليون كيلومتر مربع. والحساب بسيط: المساحة ÷ مساحة البكسل الواحد.', Visual: V2.V_Area},
      {kicker: 'دقة 30 م', title: 'كل بكسل = 900 م²', body: 'صورة واحدة كاملة للمملكة تحتاج نحو 2.4 مليار بكسل.', Visual: V2.pixelCount('space/jeddah-px30.png', '30 متراً', '2.4', 'مليار')},
      {kicker: 'دقة 10 م', title: 'كل بكسل = 100 م²', body: 'الرقم يقفز إلى 21.5 مليار بكسل… تسعة أضعاف تقريباً.', Visual: V2.pixelCount('space/jeddah-px10.png', '10 أمتار', '21.5', 'مليار')},
      {kicker: 'دقة نصف متر', title: 'كل بكسل = ربع متر مربع', body: 'نحو 8.6 تريليون بكسل لصورة واحدة… وهنا تبدأ تحديات التخزين والمعالجة.', Visual: V2.pixelCount('space/jeddah.jpg', 'نصف متر', '8.6', 'تريليون')},
    ],
    takeaway: 'دقة أعلى = بيانات أكبر… وقدرة معالجة أكبر',
    music: 'music/digital-lemonade.mp3',
    volume: 0.25,
    source: `Figures computed from ≈2.15 million km² · Imagery: NASA ISS crew photography · ${MAC} — "Digital Lemonade"`,
  },
  ep13: {
    n: '13',
    hook: 'لماذا تظهر الحقول حمراء… في الصور الفضائية؟',
    hookEn: 'Why do fields look red in satellite images?',
    HookVisual: V.V_Jowf,
    beats: [
      {kicker: 'الألوان الطبيعية', title: 'كما تراها العين', body: 'نعرض النطاقات الأحمر والأخضر والأزرق في أماكنها، فتبدو الصورة كصورة الجوال.', Visual: V3.channelMap('natural')},
      {kicker: 'الألوان الكاذبة', title: 'نعرض ما لا تراه العين', body: 'نضع نطاق الأشعة تحت الحمراء القريبة في قناة اللون الأحمر على الشاشة.', Visual: V3.channelMap('false')},
      {kicker: 'النتيجة', title: 'النبات الصحي يتوهّج بالأحمر', body: 'لأن النبات يعكس الأشعة تحت الحمراء بقوة، تظهر الحقول والمزارع حمراء زاهية وسط الصحراء.', Visual: V.V_Jowf},
      {kicker: 'الفائدة', title: 'لماذا نستخدمها؟', body: 'لتمييز النبات عن غيره بسهولة، وكشف الفروق في صحته، والفصل بين الماء واليابسة.', Visual: () => V.Chips({items: [['تمييز النبات', 'Vegetation'], ['صحة المحاصيل', 'Crop health'], ['حدود المياه', 'Water bodies'], ['المناطق العمرانية', 'Urban areas']]})},
    ],
    takeaway: 'الألوان «الكاذبة»… تكشف حقائق',
    music: 'music/clean-soul.mp3',
    volume: 0.4,
    trimBefore: 60,
    source: `Imagery: NASA/JPL (Terra ASTER, Landsat) · ${MAC} — "Clean Soul"`,
  },
  ep14: {
    n: '14',
    hook: 'لماذا لا تطابق الصورة الفضائية الخريطة… مباشرة؟',
    hookEn: 'Why doesn’t a raw satellite image match the map?',
    HookVisual: V3.V_Ortho,
    beats: [
      {kicker: 'السبب', title: 'الزاوية والتضاريس', body: 'القمر لا يصوّر دائماً من فوق المكان تماماً، والجبال المرتفعة تظهر مزاحة عن موقعها الحقيقي.', Visual: V3.V_Distort},
      {kicker: 'المرجع', title: 'نقاط تحكم أرضية', body: 'نستعين بنقاط معروفة الإحداثيات بدقة، مثل تقاطعات الطرق، لربط الصورة بالأرض.', Visual: V3.V_GCP},
      {kicker: 'التصحيح', title: 'التصحيح الهندسي (Orthorectification)', body: 'باستخدام نموذج الارتفاع ونقاط التحكم، نعيد كل بكسل إلى موقعه الصحيح على الخريطة.', Visual: V3.V_Ortho},
      {kicker: 'الأهمية', title: 'بدون تصحيح… لا قياس دقيق', body: 'قياس المسافات والمساحات، ومقارنة الصور عبر الزمن، وتحديث الخرائط… كلها تحتاج صوراً مصحّحة.', Visual: () => V.Chips({items: [['قياس المساحات', 'Area measurement'], ['رصد التغيّر', 'Change detection'], ['تحديث الخرائط', 'Map updates'], ['المشاريع الهندسية', 'Engineering']]})},
    ],
    takeaway: 'الصورة الجميلة لا تكفي… يجب أن تكون في مكانها',
    music: 'music/tech-talk.mp3',
    volume: 0.25,
    trimBefore: 30,
    source: `Imagery: NASA/JPL PIA11087 · Distortion shown is illustrative · ${MAC} — "Tech Talk"`,
  },
  ep15: {
    n: '15',
    hook: 'رقمان فقط… يحددان أي مكان على الأرض',
    hookEn: 'Two numbers can pin any place on Earth',
    HookVisual: V3.V_Graticule,
    beats: [
      {kicker: 'دائرة العرض', title: 'شمالاً أو جنوباً', body: 'تبدأ من خط الاستواء (0°) حتى القطبين (90°). الدرجة الواحدة تساوي نحو 111 كم.', Visual: V3.V_Graticule},
      {kicker: 'خط الطول', title: 'شرقاً أو غرباً', body: 'يبدأ من خط غرينتش (0°) حتى 180° شرقاً أو غرباً.', Visual: V3.V_Graticule},
      {kicker: 'مثال', title: 'الرياض بالأرقام', body: 'نحو 24.71° شمالاً و46.67° شرقاً. هذان الرقمان يكفيان ليجدها أي نظام خرائط في العالم.', Visual: V3.V_Riyadh},
      {kicker: 'الدقة', title: 'كل خانة عشرية تفرق', body: 'كلما زادت الخانات العشرية ضاق المكان: من نحو 11 كم… إلى نحو متر واحد.', Visual: V3.V_Decimals},
    ],
    takeaway: 'الإحداثية… لغة مشتركة بين كل الخرائط',
    music: 'music/inspired.mp3',
    volume: 0.3,
    trimBefore: 60,
    source: `Imagery: NASA ISS crew photography · Distances approximate (latitude) · ${MAC} — "Inspired"`,
  },
  ep16: {
    n: '16',
    hook: 'كيف تبدو العاصفة الغبارية… من الفضاء؟',
    hookEn: 'What does a dust storm look like from space?',
    HookVisual: () => V.Photo({src: 'space/gulf-dust-iss.jpg', zoom: [1.0, 1.2]}),
    beats: [
      {kicker: 'المشهد', title: 'غبار يغطي الخليج', body: 'صورة من محطة الفضاء الدولية: الغبار يحجب الخليج العربي وسواحله الشمالية.', Visual: () => V.Photo({src: 'space/gulf-dust-iss.jpg', zoom: [1.2, 1.05], pos: '40% 60%'})},
      {kicker: 'قبل وبعد', title: 'المكان نفسه… يومان مختلفان', body: 'يوم صافٍ في أبريل 2004، ثم عاصفة غبارية في مايو من القمر Terra.', Visual: V3.V_DustCompare},
      {kicker: 'القياس', title: 'كم كثافة الغبار؟', body: 'تقيس المستشعرات «العمق البصري»، أي مقدار ما يحجبه الغبار من ضوء الشمس.', Visual: V3.V_DustDepth},
      {kicker: 'الاستخدامات', title: 'لماذا نرصده؟', body: 'للتنبيهات الصحية، وسلامة الطيران، والتخطيط لتنظيف الألواح الشمسية، وتحسين التنبؤات الجوية.', Visual: () => V.Chips({items: [['التنبيهات الصحية', 'Health alerts'], ['سلامة الطيران', 'Aviation safety'], ['الألواح الشمسية', 'Solar O&M'], ['التنبؤ الجوي', 'Forecasting']]})},
    ],
    takeaway: 'ما تحمله الرياح… تراه الأقمار',
    music: 'music/interloper.mp3',
    volume: 0.35,
    trimBefore: 20,
    source: `Imagery: NASA ISS crew photography · NASA/JPL PIA04360 (Terra MISR) · ${MAC} — "Interloper"`,
  },
  ep17: {
    n: '17',
    hook: 'أين نبني محطة الطاقة الشمسية القادمة؟',
    hookEn: 'Where should the next solar plant go?',
    HookVisual: () => V.Photo({src: 'textures/arabia-day.jpg', zoom: [1.0, 1.15]}),
    beats: [
      {kicker: 'المعايير', title: 'كل معيار… طبقة', body: 'نجمع طبقات بيانات: الإشعاع الشمسي، وانحدار الأرض، والقرب من شبكة الكهرباء والطرق.', Visual: V3.V_Layers},
      {kicker: 'الأوزان', title: 'لكل معيار وزن', body: 'يحدد الخبراء أهمية كل معيار، ثم تُجمع الطبقات خلية بخلية في خريطة واحدة.', Visual: V3.V_Suitability},
      {kicker: 'القيود', title: 'ونستبعد ما لا يصلح', body: 'المحميات، والمناطق العمرانية، ومجاري السيول… تُحذف من الخريطة قبل اختيار المواقع.', Visual: () => V.Chips({items: [['المحميات', 'Protected areas'], ['العمران', 'Urban areas'], ['مجاري السيول', 'Flood channels'], ['الكثبان المتحركة', 'Moving dunes']]})},
      {kicker: 'النتيجة', title: 'قائمة مواقع مرشّحة', body: 'خريطة الملاءمة لا تتخذ القرار، لكنها تختصر البحث من آلاف الكيلومترات إلى مواقع معدودة.', Visual: V3.V_Suitability},
    ],
    takeaway: 'القرار الذكي… يبدأ بخريطة',
    music: 'music/rising-game.mp3',
    volume: 0.3,
    source: `Layers & weights are illustrative · Imagery: NASA Blue Marble · ${MAC} — "Rising Game"`,
  },
  ep18: {
    n: '18',
    hook: 'من يعدّ آلاف الحقول… في ثوانٍ؟',
    hookEn: 'Who counts thousands of fields in seconds?',
    HookVisual: V3.V_Detect,
    beats: [
      {kicker: 'التحدي', title: 'صور أكثر من أن يراها البشر', body: 'الأقمار تلتقط كل يوم مساحات هائلة، ولا يمكن لفريق بشري أن يفحصها كلها يدوياً.', Visual: () => V.Photo({src: 'space/al-jowf-pivots.jpg', zoom: [1.0, 1.25]})},
      {kicker: 'الطريقة', title: 'نماذج تتعلم من الأمثلة', body: 'ندرّب نموذج ذكاء اصطناعي على أمثلة معلّمة، ثم يكتشف المعالم المشابهة تلقائياً، ويراجع الخبراء النتائج.', Visual: V3.V_Train},
      {kicker: 'مثال', title: 'اكتشاف الحقول الدائرية', body: 'النموذج يرسم مربعاً حول كل حقل ويعطيه درجة ثقة، فيصبح العد والقياس فورياً.', Visual: V3.V_Detect},
      {kicker: 'الاستخدامات', title: 'ماذا يكتشف أيضاً؟', body: 'المباني الجديدة، والطرق، والسفن، والألواح الشمسية، والتغيّر بين صورتين.', Visual: () => V.Chips({items: [['المباني', 'Buildings'], ['الطرق', 'Roads'], ['السفن', 'Ships'], ['رصد التغيّر', 'Change detection']]})},
    ],
    takeaway: 'الذكاء الاصطناعي يقرأ الصورة… والخبير يقرر',
    music: 'music/digital-lemonade.mp3',
    volume: 0.25,
    trimBefore: 30,
    source: `Detection overlay is illustrative · Imagery: NASA/JPL (ASTER) · ${MAC} — "Digital Lemonade"`,
  },
  ep19: {
    n: '19',
    hook: 'الصورة الفضائية… لا تُلتقط دفعة واحدة',
    hookEn: 'A satellite image isn’t taken all at once',
    HookVisual: V3.V_Swath,
    beats: [
      {kicker: 'المسح', title: 'خطاً بعد خط', body: 'كثير من المستشعرات تلتقط سطراً واحداً عرضياً في كل لحظة، وحركة القمر للأمام تكمل الصورة.', Visual: V3.V_Swath},
      {kicker: 'عرض الشريط', title: 'كم يغطي في كل مرور؟', body: 'شريط Landsat عرضه نحو 185 كم، وشريط Sentinel-2 نحو 290 كم.', Visual: V3.V_SwathWidths},
      {kicker: 'التغطية', title: 'شريط بجانب شريط', body: 'الأرض تدور تحت القمر، فيمر كل يوم فوق شرائط جديدة حتى يغطي الكوكب كله.', Visual: V3.V_Swath},
      {kicker: 'الموازنة', title: 'العرض مقابل الدقة', body: 'الشريط الأعرض يعني عودة أسرع للمكان، لكن غالباً بدقة أقل. والتصميم موازنة بين الاثنين.', Visual: V3.V_SwathWidths},
    ],
    takeaway: 'كل صورة كبيرة… شرائط صغيرة متتالية',
    music: 'music/ice-flow.mp3',
    volume: 0.25,
    source: `Imagery: NASA Terra · Scanning animation illustrative · ${MAC} — "Ice Flow"`,
  },
  ep20: {
    n: '20',
    hook: 'صورة الأرض بلا غيوم… ليست لقطة واحدة',
    hookEn: 'A cloud-free Earth is not a single snapshot',
    HookVisual: V3.V_Composite,
    beats: [
      {kicker: 'الواقع', title: 'الغيوم في كل مكان', body: 'في أي لحظة، تغطي الغيوم نحو ثلثي سطح الأرض.', Visual: V3.cloudyTile(0)},
      {kicker: 'الفكرة', title: 'نصوّر المكان أياماً متتالية', body: 'كل يوم تكون الغيوم في مكان مختلف، فتظهر أجزاء مختلفة من الأرض صافية.', Visual: V3.cloudyTile(1)},
      {kicker: 'التركيب', title: 'نختار أصفى بكسل', body: 'لكل موقع، نختار البكسل الأصفى من بين الأيام، ونركّب منها صورة واحدة.', Visual: V3.V_Composite},
      {kicker: 'مثال', title: 'هكذا صُنعت «الرخامة الزرقاء»', body: 'صور NASA الشهيرة للأرض بلا غيوم هي صور مركّبة من بيانات أيام عديدة.', Visual: () => V.Photo({src: 'textures/arabia-day.jpg', zoom: [1.2, 1.0]})},
    ],
    takeaway: 'الصورة المثالية… تُبنى من صور كثيرة',
    music: 'music/floating-cities.mp3',
    volume: 0.35,
    trimBefore: 60,
    source: `Imagery: NASA Blue Marble NG (composite) · Clouds: NASA Visible Earth · ${MAC} — "Floating Cities"`,
  },
};

export const epFrames = (id: string) => episodeFrames(EPISODES[id]);
export const EpisodeById: React.FC<{id: string}> = ({id}) => createElement(EpisodeShell, {e: EPISODES[id]});
